import { Somethings } from './types'

const initialStore: Array<Somethings> = [
    {
      id: 1,
      name: "Kablonet",
      description: "Turksat Kablonet internet ödemesi",
      date: "2020-01-02",
      amount: "120",
      currency: "TRY",
    },
    {
      id: 2,
      name: "Turkcell",
      description: "Turkcell fatura ödemesi",
      date: "2020-07-09",
      amount: "50",
      currency: "TRY",
    },
    {
      id: 3,
      name: "Doğalgaz",
      description: "Doğalgaz fatura ödemesi",
      date: "2020-07-09",
      amount: "200",
      currency: "TRY",
    },
    {
      id: 4,
      name: "Elektrik",
      description: "Elektrik fatura ödemesi",
      date: "2020-07-09",
      amount: "120",
      currency: "TRY",
    },
    {
      id: 5,
      name: "Su",
      description: "Su fatura ödemesi",
      date: "2020-07-09",
      amount: "70",
      currency: "TRY",
    },
    {
      id: 6,
      name: "Vodafone",
      description: "Vodafone fatura ödemesi",
      date: "2020-02-06",
      amount: "40",
      currency: "TRY",
    },
    {
      id: 7,
      name: "Kira",
      description: "Kira ödemesi",
      date: "2020-03-01",
      amount: "2500",
      currency: "TRY",
    },
    {
      id: 8,
      name: "Amazon",
      description: "Amazon - Bluetooth kablosuz kulaklık",
      date: "2020-03-07",
      amount: "65",
      currency: "USD",
    },
    {
      id: 9,
      name: "Market",
      description: "Market Alışverişi",
      date: "2020-03-08",
      amount: "107,90",
      currency: "TRY",
    },
    {
      id: 10,
      name: "Taksit",
      description: "Taksit - Laptop 3/4 taksit ödemesi",
      date: "2020-03-16",
      amount: "1500",
      currency: "TRY",
    },
  ];
  export default initialStore